### ISSUE TITLE
Consider when upgrade okhttp version to 2.6.0?

### ISSUE THREAD

**Issue by hamberluo** [socketio/socket.io-client-java#261]

**Comment by saidBeekast** [comment]
Hi, I think I've got a problem linked to this : 
That's what I get when I try to connect to the server : 

Exception in thread "EventThread" java.lang.NoClassDefFoundError: com/squareup/okhttp/ws/WebSocketListener
	at io.socket.engineio.client.Socket.createTransport(Socket.java:269)
	at io.socket.engineio.client.Socket.probe(Socket.java:317)
	at io.socket.engineio.client.Socket.onOpen(Socket.java:472)
	at io.socket.engineio.client.Socket.onHandshake(Socket.java:512)
	at io.socket.engineio.client.Socket.onPacket(Socket.java:486)
	at io.socket.engineio.client.Socket.access$900(Socket.java:30)
	at io.socket.engineio.client.Socket$5.call(Socket.java:300)
	at io.socket.emitter.Emitter.emit(Emitter.java:117)
	at io.socket.engineio.client.Transport.onPacket(Transport.java:129)
	at io.socket.engineio.client.transports.Polling.access$700(Polling.java:17)
	at io.socket.engineio.client.transports.Polling$2.call(Polling.java:124)
	at io.socket.engineio.parser.Parser.decodePayload(Parser.java:251)
	at io.socket.engineio.client.transports.Polling._onData(Polling.java:134)
	at io.socket.engineio.client.transports.Polling.onData(Polling.java:106)
	at io.socket.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:113)
	at io.socket.thread.EventThread$2.run(EventThread.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.squareup.okhttp.ws.WebSocketListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more

Any workaround to fix this please?

Thanks

**Comment by nkzawa** [comment]
v0.6.3 has just been released :) it uses okhttp 2.7.0
